version: '3.7'

services:
  traefik:
    image: traefik:2.0
    command:
      - '--log.level=INFO'
      #- '--accesslog=true'
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.swarmmode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=launch-net'
      - '--entrypoints.web.address=:80'
      #- '--entrypoints.websecure.address=:443'
      #- '--certificatesresolvers.httpchallengeresolver.acme.httpchallenge=true'
      #- '--certificatesresolvers.httpchallengeresolver.acme.httpchallenge.entrypoint=web'
      #- '--certificatesresolvers.httpchallengeresolver.acme.email=user@domain.com'
      #- '--certificatesresolvers.httpchallengeresolver.acme.storage=/acme.json'
    ports:
      - ${ROUTER_HTTP_PORT}:80
      - ${ROUTER_HTTPS_PORT}:443
      - ${ROUTER_MONITOR_PORT}:8080
    networks:
      - launch-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${LAUNCH_ROOTPATH}/traefik/acme.json:/acme.json
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  launch-net:
    external: true
