version: '3'

services:
  registry:
    image: registry:2
    ports:
      - ${REGISTRY_PORT}:5000
    networks:
      - launch-net
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ${LAUNCH_ROOTPATH}/registry/data:/var/lib/registry
      - ${LAUNCH_ROOTPATH}/registry/auth:/auth
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  launch-net:
    external: true
