version: '3'

services:
  traefik:
    image: traefik:1.7
    ports:
      - ${ROUTER_HTTP_PORT}:80
      - ${ROUTER_HTTPS_PORT}:443
      - ${ROUTER_MONITOR_PORT}:8080
    networks:
      - launch-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LAUNCH_ROOTPATH}/traefik/traefik.toml:/traefik.toml
      - ${LAUNCH_ROOTPATH}/traefik/acme.json:/acme.json
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  launch-net:
    external: true
