version: '3'

services:
  registry:
    image: registry:2
    ports:
      - 5050:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ${GOV_ROOTPATH}/registry/data:/var/lib/registry
      - ${GOV_ROOTPATH}/registry/auth:/auth
