version: '3.7'

services:
  whoami:
    image: containous/whoami
    networks:
      - launch-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=launch-net"
        - "traefik.port=80"

networks:
  launch-net:
    external: true
