version: '3.7'

services:
  whoami:
    image: containous/whoami
    networks:
      - launch-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=launch-net'
        - 'traefik.http.routers.whoami.entrypoints=web'
        - 'traefik.http.routers.whoami.rule=Host(`whoami.localhost`)'
        - 'traefik.http.services.whoami.loadbalancer.server.port=80'

networks:
  launch-net:
    external: true
