. ./source.sh

printf "\n# General options\n"

echo LAUNCH_ROOTPATH=$LAUNCH_ROOTPATH
echo LAUNCH_NETWORK=$LAUNCH_NETWORK

printf "\n# Registry\n"

echo REGISTRY_PORT=$REGISTRY_PORT
echo REGISTRY_PASSWORD_COST=$REGISTRY_PASSWORD_COST
echo REGISTRY_USERNAME=$REGISTRY_USERNAME

printf "\n# Router\n"

echo ROUTER_HTTP_PORT=$ROUTER_HTTP_PORT
echo ROUTER_HTTPS_PORT=$ROUTER_HTTPS_PORT
echo ROUTER_MONITOR_PORT=$ROUTER_MONITOR_PORT
