export LAUNCH_ROOTPATH="$(pwd)/data"
export LAUNCH_NETWORK=launch-net

export REGISTRY_PORT=5050
export REGISTRY_PASSWORD_COST=12
export REGISTRY_USERNAME=admin

export ROUTER_HTTP_PORT=8080
export ROUTER_HTTPS_PORT=8443
export ROUTER_MONITOR_PORT=4242
